In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import sklearn.metrics
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm

In [2]:
df=pd.read_csv('diamonds.csv')

In [3]:
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [4]:
df1=df.drop(['color'],axis=1)

In [5]:
df1.head()

   carat      cut clarity  depth  table  price     x     y     z
0   0.23    Ideal     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     SI2   63.3   58.0    335  4.34  4.35  2.75

In [6]:
df2=df1.drop(['cut'],axis=1)
df2

       carat clarity  depth  table  price     x     y     z
0       0.23     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 8 columns]

In [7]:
df3=df2.drop(['carat'],axis=1)

In [8]:
df3

      clarity  depth  table  price     x     y     z
0         SI2   61.5   55.0    326  3.95  3.98  2.43
1         SI1   59.8   61.0    326  3.89  3.84  2.31
2         VS1   56.9   65.0    327  4.05  4.07  2.31
3         VS2   62.4   58.0    334  4.20  4.23  2.63
4         SI2   63.3   58.0    335  4.34  4.35  2.75
...       ...    ...    ...    ...   ...   ...   ...
53935     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 7 columns]

In [9]:
df5=df3.drop(['x'],axis=1)

In [10]:
df5

      clarity  depth  table  price     y     z
0         SI2   61.5   55.0    326  3.98  2.43
1         SI1   59.8   61.0    326  3.84  2.31
2         VS1   56.9   65.0    327  4.07  2.31
3         VS2   62.4   58.0    334  4.23  2.63
4         SI2   63.3   58.0    335  4.35  2.75
...       ...    ...    ...    ...   ...   ...
53935     SI1   60.8   57.0   2757  5.76  3.50
53936     SI1   63.1   55.0   2757  5.75  3.61
53937     SI1   62.8   60.0   2757  5.68  3.56
53938     SI2   61.0   58.0   2757  6.12  3.74
53939     SI2   62.2   55.0   2757  5.87  3.64

[53940 rows x 6 columns]

In [11]:
df6=df5.drop(['y'],axis=1)

In [12]:
df6

      clarity  depth  table  price     z
0         SI2   61.5   55.0    326  2.43
1         SI1   59.8   61.0    326  2.31
2         VS1   56.9   65.0    327  2.31
3         VS2   62.4   58.0    334  2.63
4         SI2   63.3   58.0    335  2.75
...       ...    ...    ...    ...   ...
53935     SI1   60.8   57.0   2757  3.50
53936     SI1   63.1   55.0   2757  3.61
53937     SI1   62.8   60.0   2757  3.56
53938     SI2   61.0   58.0   2757  3.74
53939     SI2   62.2   55.0   2757  3.64

[53940 rows x 5 columns]

In [13]:
df7=df6.drop(['z'],axis=1)

In [14]:
df8=df7.drop(['table'],axis=1)

In [15]:
df9=df8.drop(['clarity'],axis=1)
df9.shape

(53940, 2)

In [16]:
df10=df9.astype({'depth':int})
df10

       depth  price
0         61    326
1         59    326
2         56    327
3         62    334
4         63    335
...      ...    ...
53935     60   2757
53936     63   2757
53937     62   2757
53938     61   2757
53939     62   2757

[53940 rows x 2 columns]

In [17]:
df10.describe()

              depth         price
count  53940.000000  53940.000000
mean      61.298480   3932.799722
std        1.455129   3989.439738
min       43.000000    326.000000
25%       61.000000    950.000000
50%       61.000000   2401.000000
75%       62.000000   5324.250000
max       79.000000  18823.000000

In [18]:

df10

       depth  price
0         61    326
1         59    326
2         56    327
3         62    334
4         63    335
...      ...    ...
53935     60   2757
53936     63   2757
53937     62   2757
53938     61   2757
53939     62   2757

[53940 rows x 2 columns]

In [19]:
df10=df10.replace('[^\d.]', '', regex=True).astype(float)

In [20]:
#Train-Test split
x=df10.drop('price',axis =1)
y=df10['price']
x_train,x_test,y_train,y_test=train_test_split(x,y, train_size=0.8)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(43152, 1)
(10788, 1)
(43152,)
(10788,)

In [21]:
model1=LinearRegression()
model1.fit(x_train,y_train)

LinearRegression()

In [22]:
model2 = KNeighborsRegressor(n_neighbors=3)
model2.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=3)

In [23]:
model3=DecisionTreeClassifier(criterion='entropy',max_depth=4)
model3.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [24]:
model4=svm.SVC(kernel='rbf',gamma='auto')
model4.fit(x_train,y_train)

SVC(gamma='auto')

In [ ]:
model5=sklearn.linear_model.LogisticRegression()
model5.fit(x_train,y_train)